name: source_gen_annotation_issue
version: 0.0.1
description: A simple console application.

dependencies:
  analyzer: '>=0.29.1 <0.30.0'
  source_gen: '^0.5.3'
  build_runner: '>=0.1.1 <0.4.0'
  build: '>=0.3.0 <0.8.0'


